name: quiz_generator
description: "EduTech Quiz Generator app"
publish_to: 'none'

version: 0.1.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Exam Portal Logo.png"

  flutter_test:
    sdk: flutter
    

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/