name: Confirm Build

env:
  app_name: edutech-quizgenerator.apk
  API_URL: http://apppracticequiz.runasp.net

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV

      - name: Install Java SDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Install Android NDK r27
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27
          link-to-sdk: true
          local-cache: true

      - name: Install Flutter and Dart SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: "Build release package"
        run: |
          echo export MOCK_API_KEY=$API_KEY >> .env
          echo export EDUTECH_SWAGGER_URL=$API_URL >> .env
          cat .env | xxd
          flutter build apk --release
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Prepare the release
        if: github.ref_type == 'tag'
        run: |
          cp build/app/outputs/apk/release/app-release.apk build/${{ env.app_name }}
          echo Renamed
          echo "app_version=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "Release ${{ env.app_name }}-$app_version on $(date)" > RELEASE.txt
          echo Generated RELEASE.txt

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: ${{ env.app_name }}-${{ env.app_version }}
          draft: false
          body_path: RELEASE.txt
          overwrite_files: false
          make_latest: true
          generate_release_notes: true
          files: |
            build/${{ env.app_name }}
